export enum EStateTypes {
	ME_REQ = 'ME_REQ',
	ME_REQ_ERROR = 'ME_REQ_ERROR',
	ME_REQ_SUCCESS = 'ME_REQ_SUCCESS',
	ME_REQ_DEFAULT = 'ME_REQ_DEFAULT',
	USER_REQ_ERROR = 'USER_REQ_ERROR',
	USER_REQ_SUCCESS = 'USER_REQ_SUCCESS',
	USER_REQ = 'USER_REQ',
}
